In [7]:
import numpy as np

x =np.array([[1,5,8], [6,3,9]], dtype=np.float64)
y =np.array([[0,3,4], [12,6,18]], dtype=np.float64)
sum1=np.add(x,y)
sum2= x + y

print(x)
print("+"*15)
print(y)
print("+"*15)
print(sum1)
print("+"*15)



[[1. 5. 8.]
 [6. 3. 9.]]
+++++++++++++++
[[ 0.  3.  4.]
 [12.  6. 18.]]
+++++++++++++++
[[ 1.  8. 12.]
 [18.  9. 27.]]
